# Generated by Django 6.0.4 on 2026-04-29 20:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tipo', models.CharField(choices=[('obra_social', 'Obra Social'), ('prepaga', 'Prepaga'), ('particular', 'Particular')], default='obra_social', max_length=20)),
                ('codigo', models.CharField(blank=True, help_text='Código interno o de PAMI', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'coberturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='DNI argentino sin puntos ni espacios', max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('numero_afiliado', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='triage.cobertura')),
            ],
            options={
                'db_table': 'pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='VisitaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('esperando_triage', 'Esperando Triage'), ('esperando_atencion', 'Esperando Atención'), ('en_atencion', 'En Atención'), ('finalizado', 'Finalizado'), ('abandono', 'Abandono')], default='esperando_triage', max_length=20)),
                ('motivo_ingreso_breve', models.CharField(help_text='Motivo breve registrado en recepción', max_length=200)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='triage.paciente')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'visitas_emergencia',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_esi', models.IntegerField(choices=[(1, 'ESI 1 - Resucitación'), (2, 'ESI 2 - Emergencia'), (3, 'ESI 3 - Urgencia'), (4, 'ESI 4 - Menos Urgente'), (5, 'ESI 5 - No Urgente')])),
                ('motivo_consulta', models.TextField()),
                ('presion_sistolica', models.IntegerField(blank=True, help_text='mmHg', null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(300)])),
                ('presion_diastolica', models.IntegerField(blank=True, help_text='mmHg', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='latidos por minuto', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(45.0)])),
                ('saturacion_o2', models.IntegerField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, help_text='respiraciones por minuto', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('dolor_eva', models.IntegerField(blank=True, help_text='Escala Visual Analógica 0-10', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('glasgow', models.IntegerField(blank=True, help_text='Escala de Coma de Glasgow', null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('via_aerea', models.CharField(choices=[('permeable', 'Permeable'), ('comprometida', 'Comprometida'), ('obstruida', 'Obstruida')], default='permeable', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('enfermero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triages_realizados', to=settings.AUTH_USER_MODEL)),
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='triage.visitaemergencia')),
            ],
            options={
                'db_table': 'triages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['dni'], name='pacientes_dni_62d047_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='pacientes_apellid_f523df_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaemergencia',
            index=models.Index(fields=['estado', 'fecha_ingreso'], name='visitas_eme_estado_b7bc24_idx'),
        ),
        migrations.AddIndex(
            model_name='visitaemergencia',
            index=models.Index(fields=['paciente', '-fecha_ingreso'], name='visitas_eme_pacient_617ea1_idx'),
        ),
    ]
